export const mdnRedirectPath = (locale: string) : Record<string, string> => ({
  // https://developer.mozilla.org/zh-CN/docs/Mozilla/Tech/Places/Using_the_Places_keywords_AP
  [`/${locale}/docs/Bookmark_Keywords`]:
    `/${locale}/docs/Archive/Mozilla/Bookmark_keywords`,
  [`/${locale}/docs/CSS/CSS_transitions`]:
    `/${locale}/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions`,
  [`/${locale}/docs/Mozilla/Add-ons/WebExtensions/Using_the_JavaScript_APIs`]:
    `/${locale}/docs/Mozilla/Add-ons/WebExtensions/API`,
  [`/${locale}/docs/Web/Reference/Events/ended`]:
    `/${locale}/docs/Web/API/HTMLMediaElement/ended_event`,
  [`/${locale}/docs/Web/API/SMSEvent`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozSmsEvent`,
  [`/${locale}/docs/Web/Reference/Events/upgradeneeded_indexedDB`]:
    `/${locale}/docs/Web/API/IDBOpenDBRequest/upgradeneeded_event`,
  [`/${locale}/docs/Alternative_style_sheets`]:
    `/${locale}/docs/Web/CSS/Alternative_style_sheets`,
  [`/${locale}/docs/Apps/Manifest`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest`,
  [`/${locale}/Firefox_OS/Developer_phone_guide/Flame`]:
    `/${locale}/docs/Archive/B2G_OS/Phone_guide/Flame`,
  [`/${locale}/docs/Web/API/TCPSocket/open`]:
    `/${locale}/docs/Archive/B2G_OS/API/TCPSocket/open`,
  [`/${locale}/docs/DOM/MozMobileConnectionInfo.relSignalStrength`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileConnectionInfo/relSignalStrength`,
  [`/${locale}/docs/Web/API/MozSettingsEvent/settingValue`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozSettingsEvent/settingValue`,
  [`/${locale}/Apps/Developing/App_permissions`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/App_permissions`,
  [`/${locale}/Apps/Build/Building_apps_for_Firefox_OS/Firefox_OS_app_beginners_tutorial`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Firefox_OS_app_beginners_tutorial`,
  [`/${locale}/docs/DOM/event.charCode`]:
    `/${locale}/docs/Web/API/KeyboardEvent/charCode`,
  [`/${locale}/WebGL`]:
    `/${locale}/docs/Web/API/WebGL_API`,
  [`/${locale}/DOM/element.tagName`]:
    `/${locale}/docs/Web/API/Element/tagName`,
  [`/${locale}/IndexedDB/IDBObjectStore`]:
    `/${locale}/docs/Web/API/IDBObjectStore`,
  [`/${locale}/docs/Web/Apps/App_templates`]:
    `/${locale}/docs/Archive/Apps/Tools_and_frameworks/App_templates`,
  [`/${locale}/docs/Security/MixedContent/fix_website_with_mixed_content`]:
    `/${locale}/docs/Security/MixedContent/How_to_fix_website_with_mixed_content`,
  [`/${locale}/docs/JavaScript/Reference/Global_Objects/Map`]:
    `/${locale}/docs/Web/JavaScript/Reference/Global_Objects/Map`,
  [`/${locale}/docs/Apps/App_permissions`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/App_permissions`,
  [`/${locale}/Apps/CSP`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/CSP`,
  [`/${locale}/docs/Web/API/MozAlarmsManager/getAll`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozAlarmsManager/getAll`,
  [`/${locale}/docs/DOM/window.clearTimeout`]:
    `/${locale}/docs/Web/API/WindowTimers/clearTimeout`,
  [`/${locale}/DOM/window.openDialog`]:
    `/${locale}/docs/Web/API/Window/openDialog`,
  // [`/${locale}/docs/XUL_School/The_Essentials_of_an_Extension`]: ``,
  [`/${locale}/Apps/Build/Manipulating_media/buffering_seeking_time_ranges`]:
    `/${locale}/docs/Web/Guide/Audio_and_video_delivery/buffering_seeking_time_ranges`,
  [`/${locale}/DOM/document.readyState`]:
    `/${locale}/docs/Web/API/Document/readyState`,
  [`/${locale}/docs/Web/CSS/:-moz-full-screen`]:
    `/${locale}/docs/Web/CSS/:fullscreen`,
  [`/${locale}/docs/DOM/CustomEvent`]:
    `/${locale}/docs/Web/API/CustomEvent`,
  [`/${locale}/DOM/Element.nextElementSibling`]:
    `/${locale}/docs/Web/API/NonDocumentTypeChildNode/nextElementSibling`,
  [`/${locale}/docs/DOM/element.nodeName`]:
    `/${locale}/docs/Web/API/Node/nodeName`,
  [`/${locale}/docs/CSS/Using_CSS_flexible_boxes`]:
    `/${locale}/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes`,
  [`/${locale}/docs/Controlling_spell_checking_in_HTML_forms`]:
    `/${locale}/docs/Web/HTML/Global_attributes/spellcheck`,
  [`/${locale}/docs/CSS/Using_URL_values_for_the_cursor_property`]:
    `/${locale}/docs/Web/CSS/cursor/url`,
  [`/${locale}/docs/DOM/Using_dynamic_styling_information`]:
    `/${locale}/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information`,
  [`/${locale}/docs/Web/CSS/-webkit-animation-fill-mode`]:
    `/${locale}/docs/Web/CSS/animation-fill-mode`,
  [`/${locale}/docs/Web/CSS/-webkit-column-rule-style`]:
    `/${locale}/docs/Web/CSS/column-rule-style`,
  [`/${locale}/docs/Web/CSS/-webkit-hyphens`]:
    `/${locale}/docs/Web/CSS/hyphens`,
  [`/${locale}/docs/Web/CSS/-moz-transform-style`]:
    `/${locale}/docs/Web/CSS/transform-style`,
  // [`/samples/webgl/sample2`]:
  //   `https://mdn.github.io/webgl-examples/tutorial/sample2/`,
  [`/${locale}/docs/Web/CSS/-moz-transition-delay`]:
    `/${locale}/docs/Web/CSS/transition-delay`,
  [`/${locale}/docs/Web/CSS/-webkit-column-width`]:
    `/${locale}/docs/Web/CSS/column-width`,
  [`/${locale}/docs/Web/CSS/-moz-transition-property`]:
    `/${locale}/docs/Web/CSS/transition-property`,
  [`/${locale}/docs/Web/CSS/-moz-perspective`]:
    `/${locale}/docs/Web/CSS/perspective`,
  [`/${locale}/docs/Web/CSS/-webkit-background-size`]:
    `/${locale}/docs/Web/CSS/background-size`,
  [`/${locale}/docs/Web/CSS/-webkit-column-span`]:
    `/${locale}/docs/Web/CSS/column-span`,
  [`/${locale}/docs/Web/CSS/-webkit-border-bottom-right-radius`]:
    `/${locale}/docs/Web/CSS/border-bottom-right-radius`,
  [`/${locale}/docs/Web/CSS/-webkit-background-clip`]:
    `/${locale}/docs/Web/CSS/background-clip`,
  [`/${locale}/docs/Web/CSS/-webkit-box-sizing`]:
    `/${locale}/docs/Web/CSS/box-sizing`,
  [`/${locale}/docs/Web/CSS/-webkit-animation-timing-function`]:
    `/${locale}/docs/Web/CSS/animation-timing-function`,
  [`/${locale}/docs/Web/CSS/-webkit-border-image`]:
    `/${locale}/docs/Web/CSS/border-image`,
  [`/${locale}/docs/Web/CSS/-webkit-column-gap`]:
    `/${locale}/docs/Web/CSS/column-gap`,
  [`/${locale}/docs/Web/CSS/-moz-transition`]:
    `/${locale}/docs/Web/CSS/transition`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/%E5%AE%9A%E4%BD%8D%E5%B1%82`]:
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/Stack_Positioning`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/%E6%A0%B7%E5%BC%8F%E5%8C%96%E6%A0%91`]:
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/Styling_a_Tree`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E7%9A%84%E7%9A%AE%E8%82%A4`]:
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/Modifying_the_Default_Skin`,
  [`/${locale}/docs/Web/CSS/-webkit-animation`]:
    `/${locale}/docs/Web/CSS/animation`,
  [`/${locale}/docs/Web/CSS/-webkit-animation-duration`]:
    `/${locale}/docs/Web/CSS/animation-duration`,
  [`/${locale}/docs/Submitting_an_add-on_to_AMO`]:
    `/${locale}/docs/Mozilla/Add-ons/Submitting_an_add-on_to_AMO`,
  [`/${locale}/docs/Web/CSS/-webkit-column-rule-color`]:
    `/${locale}/docs/Web/CSS/column-rule-color`,
  [`/${locale}/docs/Web/API/Web_Animations_API/Animation_timing_options`]:
    `/${locale}/docs/Web/API/EffectTiming`,
  [`/${locale}/docs/Web/API/MozMobileMessageManager/send`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileMessageManager/send`,
  [`/${locale}/docs/Apps/Updating_apps`]:
    `/${locale}/docs/Archive/Mozilla/Marketplace/Publishing/Updating_apps`,
  [`/${locale}/docs/Web/API/DOMCursor/done`]:
    `/${locale}/docs/Archive/B2G_OS/API/DOMCursor/done`,
  [`/${locale}/docs/Web/API/DOMCursor/continue`]:
    `/${locale}/docs/Archive/B2G_OS/API/DOMCursor/continue`,
  [`/${locale}/docs/Web/API/MozContact/bday`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozContact/bday`,
  [`/${locale}/docs/Web/API/MozContact/published`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozContact/published`,
  [`/${locale}/docs/Web/API/PowerManager/getWakeLockState`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozPowerManager/getWakeLockState`,
  [`/${locale}/docs/Web/API/MozContact/init`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozContact/init`,
  [`/${locale}/docs/Web/API/MozWifiConnectionInfoEvent/network`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozWifiConnectionInfoEvent/network`,
  [`/${locale}/docs/Web/API/MozContact/jobTitle`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozContact/jobTitle`,
  [`/${locale}/docs/Web/API/MozPowerManager/removeWakeLockListener`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozPowerManager/removeWakeLockListener`,
  [`/${locale}/docs/Project:The_Kuma_API`]:
    `/${locale}/docs/MDN/Contribute/Tools/Document_parameters`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/MozActivityRequestHandler`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozActivityRequestHandler`,
  [`/${locale}/docs/NsIInputStream`]:
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIInputStream`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/MozActivityOptions`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozActivityOptions`,
  [`/${locale}/docs/Web/Apps/JavaScript_API/navigator.mozApps.mgmt.clearWatch`]:
    `/${locale}/docs/Archive/Marketplace/API/DOMApplicationsManager/clearWatch`,
  [`/${locale}/Apps/JavaScript_API`]:
    `/${locale}/docs/Archive/Marketplace/API/App_installation_and_management_APIs`,
  [`/${locale}/docs/Web/API/DeviceStorage/default`]:
    `/${locale}/docs/Archive/B2G_OS/API/DeviceStorage/default`,
  [`/${locale}/docs/Web/Apps/JavaScript_API/navigator.mozApps.mgmt.watchUpdates`]:
    `/${locale}/docs/Archive/Marketplace/API/DOMApplicationsManager/watchUpdates`,
  [`/${locale}/docs/Web/Apps/JavaScript_API/navigator.mozApps.mgmt.list`]:
    `/${locale}/docs/Archive/Marketplace/API/DOMApplicationsManager/list`,
  [`/${locale}/docs/Web/API/Apps.getInstalled`]:
    `/${locale}/docs/Archive/Marketplace/API/DOMApplicationsRegistry/getInstalled`,
  [`/${locale}/docs/Web/CSS/-moz-transition-duration`]:
    `/${locale}/docs/Web/CSS/transition-duration`,
  [`/${locale}/docs/Web/API/window.navigator.mozApps`]:
    `/${locale}/docs/Archive/B2G_OS/API/Navigator/mozApps`,
  [`/${locale}/Apps/Manifest`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest`,
  [`/${locale}/docs/Web/API/MozContact/email`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozContact/email`,
  [`/${locale}/docs/Web/API/SmsMessage`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozSmsMessage`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/MozActivity`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozActivity`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/Tree_Box_Objects`]:
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/More_Wizards`,
  [`/${locale}/docs/Web/API/MozWifiConnectionInfoEvent/linkSpeed`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozWifiConnectionInfoEvent/linkSpeed`,
  [`/${locale}/docs/Gecko_User_Agent_Strings`]:
    `/${locale}/docs/Web/HTTP/Headers/User-Agent/Firefox`,
  [`/${locale}/docs/Web/API/CameraCapabilities/recorderProfiles`]:
    `/${locale}/docs/Archive/B2G_OS/API/CameraCapabilities/recorderProfiles`,
  [`/${locale}/docs/Web/API/MozWifiStatusChangeEvent/status`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozWifiStatusChangeEvent/status`,
  [`/${locale}/docs/Web/API/MozWifiConnectionInfoEvent/signalStrength`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozWifiConnectionInfoEvent/signalStrength`,
  [`/${locale}/docs/Web/API/MozMobileCFInfo/serviceClass`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileCFInfo/serviceClass`,
  [`/${locale}/docs/Web/API/MozMobileCFInfo/reason`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileCFInfo/reason`,
  [`/${locale}/docs/Web/API/MozMobileCellInfo/gsmCellId`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileCellInfo/gsmCellId`,
  [`/${locale}/docs/Web/API/MozMobileICCInfo/spn`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileCCInfo/spn`,
  [`/${locale}/docs/Web/API/MozMobileCFInfo/number`]:
    `/${locale}/docs/Archive/B2G_OS/API/MozMobileCFInfo/number`,
  [`/${locale}/docs/XUL/Property/valueNumber`]:
    `/${locale}/docs/Archive/Mozilla/XUL/Property/valueNumber`,
  // [`/${locale}/Gecko_Plugin_API_Reference/Plug-in_Development_Overview`]:`404`,
  [`/${locale}/docs/Web/CSS/dominant-baseline`]:
    `/${locale}/docs/Web/SVG/Attribute/dominant-baseline`,
  [`/${locale}/docs/Web/API/Telephony/active`]:
    `/${locale}/docs/Archive/B2G_OS/API/Telephony/active`,
  [`/${locale}/docs/Web/Guide/Telephony`]:
    `/${locale}/docs/Archive/B2G_OS/Web_Telephony_API`,
  [`/${locale}/docs/Web/CSS/-webkit-perspective`]:
    `/${locale}/docs/Web/CSS/perspective`,
  [`/${locale}/Apps/Build/installable_apps/App_manifest_FAQ`]:
    `/${locale}/docs/Archive/B2G_OS/Firefox_OS_apps/App_development_FAQ`,
  [`/${locale}/Apps/app_layout/responsive_design_building_blocks`]:
    `/${locale}/docs/Web/Progressive_web_apps/Responsive/responsive_design_building_blocks`,
  [`/${locale}/docs/Mozilla/Firefox_OS/Phone`]:
    `/${locale}/docs/Archive/B2G_OS/Phone_guide/Phone_specs`,
  [`/${locale}/docs/nsIConsoleService`]:
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIConsoleService`,
  [`/${locale}/docs/JavaScript/Guide/LiveConnect_Overview`]:
    `/${locale}/docs/Archive/Web/LiveConnect`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/BluetoothGattService`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothGattService`,
  [`/${locale}/docs/Web/API/Web_Bluetooth_API/Using_the_Web_Bluetooth_API`]:
    `/${locale}/docs/Archive/B2G_OS/Bluetooth_API/Using_the_Web_Bluetooth_API`,
  [`/${locale}/docs/Web/API/BluetoothGattService_%28Firefox_OS%29`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothGattService`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/BluetoothDeviceEvent`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothDeviceEvent`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/BluetoothGattCharacteristic`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothGattCharacteristic`,
  [`/${locale}/docs/Mozilla/Firefox_OS/API/BluetoothGattCharacteristicEvent`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothGattCharacteristicEvent`,
  [`/${locale}/docs/DOM/CSS`]:
    `/${locale}/docs/Web/CSS/Reference`,
  [`/${locale}/docs/Web/CSS/-webkit-transform-style`]:
    `/${locale}/docs/Web/CSS/transform-style`,
  [`/${locale}/docs/NSPR_API_Reference:Floating_Point_Number_to_String_Conversion`]:
    `/${locale}/docs/Mozilla/Projects/NSPR/Reference/Floating_Point_Number_to_String_Conversion`,
  [`/${locale}/docs/Site_Author_Guide_for_Click-To-Activate_Plugins`]:
    `/${locale}/docs/Plugins/Flash_Activation:_Browser_Comparison`,
  [`/${locale}/Gecko_Plugin_API_Reference`]:
    `/${locale}/docs/Mozilla/Add-ons/Plugins/Plugin_API_Reference`,
  [`/${locale}/DOM/document.async`]:
    `/${locale}/docs/Web/API/XMLDocument/async`,
  [`/${locale}/docs/Project:Custom_templates`]:
    `/${locale}/docs/MDN/Contribute/Content/Custom_macros`,
  [`/${locale}/docs/Project:MDN/Contributing/Custom_macros`]:
    `/${locale}/docs/MDN/Contribute/Content/Custom_macros`,
  [`/${locale}/Add-ons/SDK/Getting_Started_With_cfx`]:
    `/${locale}/docs/Mozilla/Add-ons/SDK/Tutorials/Getting_started`,
  [`/${locale}/docs/Code_snippets/Tree`]:
    `/${locale}/docs/Archive/Add-ons/Code_snippets/Tree`,
  [`/${locale}/docs/XUL/School_tutorial/Adding_Toolbars_and_Toolbar_Buttons`]:
    `/${locale}/docs/Mozilla/Add-ons/Overlay_Extensions/XUL_School/Adding_Toolbars_and_Toolbar_Buttons`,
  [`/${locale}/Apps/App_developer_tools`]:
    `/${locale}/docs/Tools`,
  [`/${locale}/Marketplace/Creating_a_store`]:
    `/${locale}/docs/Archive/Marketplace/Options/Creating_a_store`,
  [`/${locale}/Marketplace/Submission/Submitting_an_app`]:
    `/${locale}/docs/Archive/Mozilla/Marketplace/Publishing/Submit/After_submission`,
  [`/${locale}/Add-ons/SDK/Tutorials/Getting_Started_With_cfx`]:
    `/${locale}/docs/Mozilla/Add-ons/SDK/Tutorials/Getting_started`,
  [`/${locale}/Apps/Build/JavaScript_API`]:
    `/${locale}/docs/Archive/Marketplace/API/App_installation_and_management_APIs`,
  [`/${locale}/Marketplace/Publishing/Marketplace_screenshot_criteria`]:
    `/${locale}/docs/Archive/Mozilla/Marketplace/Publishing/Policies_and_Guidelines/Marketplace_screenshot_criteria`,
  [`/${locale}/docs/Web/Apps/FAQs/About_app_manifests`]:
    `/${locale}/docs/Web/Apps/Build/installable_apps_for_Firefox_OS/App_manifest_FAQ`,
  [`/${locale}/Marketplace/Prepare_For_Success/Getting_to_know_your_users`]:
    `/${locale}/docs/Archive/Mozilla/Marketplace/Prepare/Getting_to_know_your_users`,
  [`/${locale}/Apps/Publishing/Marketplace_screenshot_criteria`]:
    `/${locale}/docs/Archive/Mozilla/Marketplace/Publishing/Policies_and_Guidelines/Marketplace_screenshot_criteria`,
  [`/${locale}/docs/Web/HTML/Canvas/Tutorial/Basic_animations`]:
    `/${locale}/docs/Web/API/Canvas_API/Tutorial/Basic_animations`,
  [`/${locale}/docs/Web/Accessibility/ATSPI_Support`]:
    `/${locale}/docs/Mozilla/Tech/Accessibility/AT-APIs`,
  [`/${locale}/docs/Core_JavaScript_1.5_Reference/Operators/Special_Operators/instanceof_Operator`]:
    `/${locale}/docs/Web/JavaScript/Reference/Operators/instanceof`,
  [`/${locale}/Add-ons/Firefox_for_Android/API/HomeProvider.jsm/HomeStorage`]:
    `/${locale}/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/HomeProvider.jsm/HomeStorage`,
  [`/${locale}/docs/XUL/Property/preferenceElements`]:
    `/${locale}/docs/Archive/Mozilla/XUL/Property/preferenceElements`,
  [`/${locale}/docs/Mozilla/Add-ons/SDK/Guides/Getting_Started`]:
    `/${locale}/docs/Archive/Add-ons/Add-on_SDK/Guides/Contributor_s_Guide/Getting_Started`,
  [`/${locale}/docs/Extensions/Mobile/API/NativeWindow/pageactions`]:
    `/${locale}/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/PageActions.jsm`,
  [`/${locale}/DOM/EventTarget`]:
    `/${locale}/docs/Web/API/EventTarget`,
  [`/${locale}/docs/Web/CSS/-webkit-animation-direction`]:
    `/${locale}/docs/Web/CSS/animation-direction`,
  [`/${locale}/docs/Mozilla/Add-ons/WebExtensions/Alternative_distribution_options/Sideloading_add-ons`]:
    `/${locale}/docs/Mozilla/Add-ons/WebExtensions/Distribution_options/Sideloading_add-ons`,
  [`/${locale}/DOM/XMLHttpRequest/FormData`]:
    `/${locale}/docs/Web/API/FormData`,
  [`/${locale}/docs/Web/Apps/Developing/Optimizing_startup_performance`]:
    `/${locale}/docs/Web/Performance/Optimizing_startup_performance`,
  [`/${locale}/docs/JavaScript`]:
    `/${locale}/docs/Web/JavaScript`,
  [`/${locale}/docs/Tools/Responsive_Design_Mode`]:
    `/${locale}/docs/Tools/Responsive_Design_View`,
  [`/${locale}/docs/nsIXMLHttpRequest`]:
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest`,
  '/@api/deki/files/272/=Moz_ffx_openStandards_1280x1024.jpg':
    '/files/559/Moz_ffx_openStandards_1280x1024.jpg',
  [`/${locale}/docs/CSS:text-align`]:
    `/${locale}/docs/Web/CSS/text-align`,
  [`/${locale}/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_property`]:
    `/${locale}/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute`,
  [`/${locale}/docs/CSS:font-size-adjust`]:
    `/${locale}/docs/Web/CSS/font-size-adjust`,
  [`/${locale}/docs/CSS:border`]:
    `/${locale}/docs/Web/CSS/border`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/%E5%85%B3%E4%BA%8EContents.rdf`]:
    `/${locale}/docs/junks/%E5%85%B3%E4%BA%8EContents.rdf`,
  [`/${locale}/docs/Web/API/DeviceStorage/storageName`]:
    `/${locale}/docs/Archive/B2G_OS/API/DeviceStorage/storageName`,
  [`/${locale}/docs/Accessibility/AT-SPI_Support`]:
    `/${locale}/docs/Mozilla/Tech/Accessibility/AT-APIs`,
  [`/${locale}/XUL_%E6%95%99%E7%A8%8B/XUL%E7%9A%84%E7%BB%93%E6%9E%84`]:
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/XUL_Structure`,
  [`/${locale}/docs/API/WebTelephony`]:
    `/${locale}/docs/Archive/B2G_OS/Web_Telephony_API`,
  [`/${locale}/docs/Accessible_DHTML`]:
    `/${locale}/docs/Web/Accessibility/ARIA`,
  [`/${locale}/docs/API/WebSMS/Introduction_to_WebSMS`]:
    `/${locale}/docs/Archive/B2G_OS/API/Mobile_Messaging_API/Introduction_to_Mobile_Message_API`,
  [`/${locale}/docs/XUL_School/Connecting_to_Remote_Content`]:
    `/${locale}/docs/Archive/Add-ons/Overlay_Extensions/XUL_School/Connecting_to_Remote_Content`,
  '/en-US/docs/Web/Events/readystatechange':
    `/${locale}/docs/Web/Events/readystatechange_event`,
  '/en-US/docs/Archive/Add-ons/Add-on_SDK/Low-Level_APIs/ui_button_toggle':
    `/${locale}/docs/Archive/Add-ons/Add-on_SDK/Low-Level_APIs/ui_button_toggle`,
  '/../../../../En/Mozilla_developer_guide':
    `/${locale}/docs/Mozilla/Developer_guide`,
  '/../../../../en/XUL_Tutorial/Localization':
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/Localization`,
  '/../../../../en/XUL_Tutorial/Document_Object_Model':
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/Document_Object_Model`,
  '/../../../../En/NsITimer':
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITimer`,
  '/../../../../en/XUL_Tutorial/More_Event_Handlers':
    `/${locale}/docs/Mozilla/Tech/XUL/Tutorial/More_Event_Handlers`,
  '/../../../../en/Using_JavaScript_code_modules':
    `/${locale}/docs/Mozilla/JavaScript_code_modules/Using`,
  '/../../../../En/nsITimer':
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITimer`,
  '/../../../../en/DOM/window.setTimeout':
    `/${locale}/docs/Web/API/Window/setTimeout`,
  '/../../../../En/Publishing_Mercurial_Clones':
    `/${locale}/docs/Mozilla/Creating_Mercurial_User_Repositories`,
  '/../../../../En/SpiderMonkey':
    `/${locale}/docs/Mozilla/Projects/SpiderMonkey`,
  '/en/nsIFeedTextConstruct':
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIFeedTextConstruct`,
  '/En/NsIAccessible/Parent':
    `/${locale}/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIAccessible/Parent`,
  '/en-US/docs/DOM/event.charCode':
    `/${locale}/docs/Web/API/KeyboardEvent/charCode`,
  [`/${locale}/docs/Web/CSS/en-US/docs/Web/API/WebVTT_API`]:
    `/${locale}/docs/Web/API/WebVTT_API`,
  // from https://developer.mozilla.org/zh-CN/docs/Glossary/JavaScript
  [`/${locale}/docs/Glossary/a%20href=%22/en-US/docs/Glossary/Microsoft_Internet_Explorer%22%20title=%22Internet%20Explorer%203.0:%20Internet%20Explorer%20%28or%20IE%29%20is%20a%20free%20graphical%20browser%20maintained%20by%20Microsoft%20for%20legacy%20enterprise%20uses.%20Microsoft%20Edge%20is%20currently%20the%20default%20Windows%20browser.%22%20class=%22glossaryLink%22%3EInternet%20Explorer%203.0%3C/a`]:
    `/${locale}/docs/Glossary/Microsoft_Internet_Explorer`,
  [`/${locale}/docs/Web/API/en-US/docs/Server-sent_events/Using_server-sent_events`]:
    `/${locale}/docs/Server-sent_events/Using_server-sent_events`,
  [`/${locale}/docs/MDN/Contribute/Localize/en-US/docs/MDN/Contribute/Tools/Template_editing`]:
    `/${locale}/docs/MDN/Contribute/Tools/Template_editing`,
  [`/${locale}/docs/Web/Accessibility/Understanding_WCAG/en-US/docs/Web/Accessibility/Understanding_WCAG`]:
    `/${locale}/docs/Web/Accessibility/Understanding_WCAG`,
  [`/${locale}/Firefox/Releases/en-US/Add-ons/SDK/Low-Level_APIs/test_httpd`]:
    `/${locale}/docs/Archive/Add-ons/Add-on_SDK/Low-Level_APIs/test_httpd`,
  [`/${locale}/docs/Web/CSS/en-US/docs/Web/CSS`]:
    `/${locale}/docs/Web/CSS`,
  [`/${locale}/docs/@api/deki/files/706/=Groupbox2.png`]:
    '/@api/deki/files/706/=Groupbox2.png',
  [`/${locale}/docs/@api/deki/files/568/=Boxfinal2.png`]:
    '/@api/deki/files/568/=Boxfinal2.png',
  [`/${locale}/docs/@api/deki/files/567/=Boxfinal1.png`]:
    '/@api/deki/files/567/=Boxfinal1.png',
  [`/${locale}/docs/@api/deki/files/891/=Titledbox1.png`]:
    '/@api/deki/files/891/=Titledbox1.png',
  '/zh-CN/docs/Glossary/%E7%94%A8%E6%88%B7%E4%BB%A3%E7%90%86':
    `/${locale}/docs/Glossary/User_Agent`,
  [`/${locale}/docs/Web/Reference/Events/slotchange`]:
    `/${locale}/docs/Web/API/HTMLSlotElement/slotchange_event`,
  [`/${locale}/Web_Development/Responsive_Web_design`]:
    `/${locale}/docs/Web_Development/Mobile/Responsive_design`,
  [`/${locale}/docs/Web/CSS/Using_CSS_gradients`]:
    `/${locale}/docs/Web/CSS/CSS_Images/Using_CSS_gradients`,
  [`/${locale}/docs/Web/API/Element/style`]:
    `/${locale}/docs/Web/API/HTMLElement/style`,
  '/zh-CN/docs/Web/Media/Overview':
    `/${locale}/docs/Web/Media`,
  '/zh-CN/Add-ons/Code_snippets/Tabbed_browser?redirectlocale=en-US&redirectslug=Code_snippets%2FTabbed_browser':
    `/${locale}/docs/Archive/Add-ons/Tabbed_browser`,
  '/zh-CN/Add-ons/Code_snippets/Tabbed_browser':
    `/${locale}/docs/Archive/Add-ons/Tabbed_browser`,
  [`/${locale}/docs/Web/Events/readystatechange`]:
    `/${locale}/docs/Web/API/Document/readystatechange_event`,
  [`/${locale}/docs/Web/API/Document/onreadystatechange`]:
    `/${locale}/docs/Web/API/Document/readystatechange_event`,
  [`/${locale}/docs/Web/API/BluetoothAdapter/startDiscovery`]:
    `/${locale}/docs/Archive/B2G_OS/API/BluetoothAdapter/startDiscovery`,
  [`/${locale}/docs/Web/API/Element/childNodes`]:
    `/${locale}/docs/Web/API/Node/childNodes`,
  [`/${locale}/docs/Web/API/Element/blur`]:
    `/${locale}/docs/Web/API/HTMLElement/blur`,
  [`/${locale}/docs/DOM/span`]:
    `/${locale}/docs/Web/HTML/Element/span`,
  [`/${locale}/docs/Web/API/span`]:
    `/${locale}/docs/Web/API/HTMLSpanElement`,
  [`/${locale}/docs/Web/HTML/Element/%20object`]:
    `/${locale}/docs/Web/HTML/Element/object`,
  [`/${locale}/docs/Web/API/Element/firstChild`]:
    `/${locale}/docs/Web/API/Node/firstChild`,
  [`/${locale}/docs/Web/API/Element/nextSibling`]:
    `/${locale}/docs/Web/API/Node/nextSibling`,
  [`/${locale}/docs/Web/API/Element/lastChild`]:
    `/${locale}/docs/Web/API/Node/lastChild`,
  [`/${locale}/docs/Web/API/Element/parentNode`]:
    `/${locale}/docs/Web/API/Node/parentNode`,
  [`/${locale}/docs/Web/API/Element/removeChild`]:
    `/${locale}/docs/Web/API/Node/removeChild`,
  [`/${locale}/docs/Web/API/Element/previousSibling`]:
    `/${locale}/docs/Web/API/Node/previousSibling`,
  [`/${locale}/docs/Web/API/Element/insertBefore`]:
    `/${locale}/docs/Web/API/Node/insertBefore`,
  [`/${locale}/docs/Web/API/Element/onclick`]:
    `/${locale}/docs/Web/API/HTMLElement/onclick`,
  [`/${locale}/docs/Web/API/TableRow/insertCell`]:
    `/${locale}/docs/Web/API/HTMLTableRowElement/insertCell`,
  [`/${locale}/docs/Web/API/Element/NodeList`]:
    `/${locale}/docs/Web/API/NodeList`,
  [`/${locale}/docs/Web/API/HTML/Element/script`]:
    `/${locale}/docs/Web/API/HTMLScriptElement`,
  [`/${locale}/SVG/Content_type`]:
    `/${locale}/docs/Web/SVG/Content_type`,
  [`/${locale}/SVG/FAQ`]:
    `/${locale}/docs/Web/SVG/FAQ`,
  [`/${locale}/SVG/Content_type`]:
    `/${locale}/docs/Web/SVG/Content_type`,
  [`/${locale}/SVG/Namespaces_Crash_Course`]:
    `/${locale}/docs/Web/SVG/Namespaces_Crash_Course`,
  [`/${locale}/SVG/Attribute`]:
    `/${locale}/docs/Web/SVG/Attribute`,
  [`/${locale}/SVG/Compatibility_sources`]:
    `/${locale}/docs/Web/SVG/Compatibility_sources`,
  [`/${locale}/SVG/Tutorial/Filter_effects`]:
    `/${locale}/docs/Web/SVG/Tutorial/Filter_effects`,
  [`/${locale}/SVG/Element/rect`]:
    `/${locale}/docs/Web/SVG/Element/rect`,
  [`/${locale}/SVG/Element/circle`]:
    `/${locale}/docs/Web/SVG/Element/circle`,
  [`/${locale}/SVG/Tutorial/Paths`]:
    `/${locale}/docs/Web/SVG/Tutorial/Paths`,
  [`/${locale}/SVG/Tutorial/Positions`]:
    `/${locale}/docs/Web/SVG/Tutorial/Positions`,
  [`/${locale}/SVG/Element/polygon`]:
    `/${locale}/docs/Web/SVG/Element/polygon`,
  [`/${locale}/SVG/Element/defs`]:
    `/${locale}/docs/Web/SVG/Element/defs`,
  [`/${locale}/SVG/Tutorial/SVG_Fonts`]:
    `/${locale}/docs/Web/SVG/Tutorial/SVG_Fonts`,
  [`/${locale}/SVG/SVG_animation_with_SMIL`]:
    `/${locale}/docs/Web/SVG/SVG_animation_with_SMIL`,
  [`/${locale}/docs/Web/HTML/Element/svg`]:
    `/${locale}/docs/Web/SVG/Element/svg`,
  [`/${locale}/docs/Web/Events/fullscreen`]:
    `/${locale}/docs/Web/API/Document/fullscreenchange_event`,
  [`/${locale}/docs/Web/JavaScript/Reference/new`]:
    `/${locale}/docs/Web/JavaScript/Reference/Operators/new`,
  [`/${locale}/docs/DOM/HTMLVideoElement`]:
    `/${locale}/docs/Web/API/HTMLVideoElement`,
  [`/${locale}/docs/Web/API/Element/NodeList`]:
    `/${locale}/docs/Web/API/NodeList`,
  [`/${locale}/docs/Web/API/Element/offsetHeight`]:
    `/${locale}/docs/Web/API/Element/offsetHeight`,
  [`/${locale}/docs/Web/API/Element/dataset`]:
    `/${locale}/docs/Web/API/HTMLElement/dataset`,
  [`/${locale}/docs/Web/API/Element/click`]:
    `/${locale}/docs/Web/API/HTMLElement/click`,
  [`/${locale}/docs/Web/API/Element/focus`]:
    `/${locale}/docs/Web/API/HTMLElement/focus`,
  [`/${locale}/docs/Web/API/Element/onkeypress`]:
    `/${locale}/docs/Web/API/HTMLElement/onkeypress`,
  [`/${locale}/docs/Web/API/Element/onkeydown`]:
    `/${locale}/docs/Web/API/HTMLElement/onkeydown`,
  [`/${locale}/docs/Web/API/Element/dir`]:
    `/${locale}/docs/Web/API/HTMLElement/dir`,
  [`/${locale}/docs/Web/API/Element/onkeyup`]:
    `/${locale}/docs/Web/API/HTMLElement/onkeyup`,
  [`/${locale}/docs/Web/API/Element/oncontextmenu`]:
    `/${locale}/docs/Web/API/HTMLElement/oncontextmenu`,
  [`/${locale}/docs/Web/API/Element/isContentEditable`]:
    `/${locale}/docs/Web/API/HTMLElement/isContentEditable`,
  [`/${locale}/docs/Web/API/Element/contenteditable`]:
    `/${locale}/docs/Web/API/HTMLElement/contentEditable`,
  [`/${locale}/docs/Web/API/Element/contentEditable`]:
    `/${locale}/docs/Web/API/HTMLElement/contentEditable`,
  [`/${locale}/docs/Web/API/Element/transitionend_event`]:
    `/${locale}/docs/Web/API/HTMLElement/transitionend_event`,
  [`/${locale}/docs/Web/API/Element/offsetWidth`]:
    `/${locale}/docs/Web/API/HTMLElement/offsetWidth`,
  [`/${locale}/docs/Web/API/Element/textContent`]:
    `/${locale}/docs/Web/API/Node/textContent`,
  [`/${locale}/docs/Web/API/Document/en/HTML/Element/a`]:
    `/${locale}/docs/Web/HTML/Element/a`,
  [`/${locale}/docs/DOM/SVGColorProfileElement`]:
    `/${locale}/docs/Web/API/SVGColorProfileElement`,
  [`/${locale}/docs/Web/HTML/Element/%3Cvideo%3E`]:
    `/${locale}/docs/Web/HTML/Element/video`,
  [`/${locale}/docs/Web/API/Element/createTextRange`]:
    `/${locale}/docs/Web/API/Document/createRange`,
  [`/${locale}/docs/Web/HTML/Element/referrer`]:
    `/${locale}/docs/Web/API/Document/referrer`,
  [`/${locale}/docs/Web/SVG/Element/foreignObjects`]:
    `/${locale}/docs/Web/SVG/Element/foreignObject`,
  [`/${locale}/docs/Web/HTML/Element/input/%3Cinput_type=_tel_%3E`]:
    `/${locale}/docs/Web/HTML/Element/input/tel`,
  [`/${locale}/docs/Web/HTML/Element/%3Cimg%3E`]:
    `/${locale}/docs/Web/HTML/Element/img`,
  [`/${locale}/docs/Web/CSS/Web/Events/pointermove`]:
    `/${locale}/docs/Web/API/HTMLElement/pointermove_event`,
  [`/${locale}/docs/Web/Reference/Events/search`]:
    `/${locale}/docs/Web/API/HTMLInputElement/search_event`,
  [`/${locale}/docs/Web/Reference/Events/message`]:
    `/${locale}/docs/Web/API/BroadcastChannel/message_event`,
  [`/${locale}/docs/Web/Reference/Events/message_%28ServiceWorker%29`]:
    `/${locale}/docs/Web/API/ServiceWorkerGlobalScope/message_event`,
  [`/${locale}/docs/Web/Reference/Events/cancel`]:
    `/${locale}/docs/Web/API/HTMLDialogElement/cancel_event`,
  [`/${locale}/docs/Web/Reference/Events/close`]:
    `/${locale}/docs/Web/API/HTMLDialogElement/close_event`,
  [`/${locale}/docs/Web/Reference/Events/FontFaceSetLoadEvent`]:
    `/${locale}/docs/Web/API/FontFaceSetLoadEvent`,
  [`/${locale}/docs/Web/Reference/Events/addtrack`]:
    `/${locale}/docs/Web/API/MediaStream/addtrack_event`,
  [`/${locale}/docs/Web/Reference/Events/muted`]:
    `/${locale}/docs/Web/API/MediaStreamTrack/mute_event`,
  [`/${locale}/docs/Web/Reference/Events/unmuted`]:
    `/${locale}/docs/Web/API/MediaStreamTrack/unmute_event`,
  [`/${locale}/docs/Web/Reference/Events/ended%20%28MediaStreamTrack%29`]:
    `/${locale}/docs/Web/API/MediaStreamTrack/ended_event`,
  [`/${locale}/docs/Web/Reference/Events/removetrack`]:
    `/${locale}/docs/Web/API/MediaStream/removetrack_event`,
  [`/${locale}/docs/Learn/WebGL`]:
    `/${locale}/docs/Web/API/WebGL_API/Tutorial`,
  [`/${locale}/docs/DOM/event/keypress`]:
    `/${locale}/docs/Web/API/Document/keypress_event`,
  [`/${locale}/docs/DOM/Event/UIEvent/KeyboardEvent`]:
    `/${locale}/docs/Web/API/KeyboardEvent`,
  [`/${locale}/docs/DOM/HTMLBaseFontElement`]:
    `/${locale}/docs/Web/API/HTMLBaseFontElement`,
  [`/${locale}/docs/Web/API/DOM_Events`]:
    `/${locale}/docs/Web/API/Document_Object_Model/Events`,
  [`/${locale}/docs/DOM/element.contextmenu`]:
    `/${locale}/docs/Web/HTML/Global_attributes/contextmenu`,
  [`/${locale}/docs/Web/DOM/Window`]:
    `/${locale}/docs/Web/API/Window`,
  [`/${locale}/docs/DOM/element.appendChild`]:
    `/${locale}/docs/Web/API/Node/appendChild`,
  [`/${locale}/docs/DOM/element.isSupported`]:
    `/${locale}/docs/Web/API/Node/isSupported`,
  [`/${locale}/docs/DOM/element.scrollHeight`]:
    `/${locale}/docs/Web/API/Element/scrollHeight`,
  [`/${locale}/docs/DOM/element.isDefaultNamespace`]:
    `/${locale}/docs/Web/API/Node/isDefaultNamespace`,
  [`/${locale}/Code_snippets/HTML_to_DOM`]:
    `/${locale}/Archive/Add-ons/Code_snippets/HTML_to_DOM`,
  [`/${locale}/DOM_Mutation_Observers`]:
    `/${locale}/docs/Web/API/MutationObserver`,
  [`/${locale}/docs/Web/API/DOM_event_reference/input`]:
    `/${locale}/docs/Web/API/InputEvent/InputEvent`,
  [`/${locale}/docs/Web/Reference/Events/abort_%28dom_abort_api%29`]:
    `/${locale}/docs/Web/API/AbortSignal/abort_event`,
  [`/${locale}/DOMString`]:
    `/${locale}/docs/Web/API/DOMString`,
  [`/${locale}/DOMParser`]:
    `/${locale}/docs/Web/API/DOMParser`,
  [`/${locale}/Session_store_API`]:
    `/${locale}/docs/Archive/Add-ons/Session_store_API`,
  [`/${locale}/docs/DOM/Using_the_Telephony_API`]:
    `/${locale}/docs/Archive/B2G_OS/Web_Telephony_API/Using_the_Web_Telephony_API`,
  [`/${locale}/docs/Web/API/Window/DOMPoint`]:
    `/${locale}/docs/Web/API/DOMPoint`,
  [`/${locale}/docs/Web/API/Window/DOMMatrix`]:
    `/${locale}/docs/Web/API/DOMMatrix`,
  [`/${locale}/docs/Web/API/Window/DOMMatrixReadOnly`]:
    `/${locale}/docs/Web/API/DOMMatrixReadOnly`,
  [`/${locale}/docs/Web/API/Window/DOMQuad`]:
    `/${locale}/docs/Web/API/DOMQuad`,
  [`/${locale}/docs/Web/API/Window/DOMRect`]:
    `/${locale}/docs/Web/API/DOMRect`,
  [`/${locale}/docs/Web/API/Window/DOMRectReadOnly`]:
    `/${locale}/docs/Web/API/DOMRectReadOnly`,
  [`/${locale}/docs/Web/JavaScript/Reference/DOMException`]:
    `/${locale}/docs/Web/API/DOMException`,
  [`/${locale}/Using_Web_Standards_in_your_Web_Pages/Using_the_W3C_DOM`]:
    `/${locale}/docs/Archive/Using_Web_Standards_in_your_Web_Pages/Using_the_W3C_DOM`
});

export const mdnLocaleRedirectPath = (locale: string): Record<string, string> => {
  if (locale !== 'zh-CN') {
    return {};
  }
  return {
    [`/${locale}/Configuring_Build_Options`]:
      `/${locale}/docs/%E9%85%8D%E7%BD%AE%E7%BC%96%E8%AF%91%E9%80%89%E9%A1%B9`,
    [`/${locale}/docs/Apps/Packaged_apps`]:
      `/${locale}/docs/Archive/Mozilla/Marketplace/Options/%E6%89%93%E5%8C%85_%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F`,
    [`/${locale}/docs/Project:MDC_editor_guide`]:
      `/${locale}/docs/Project:MDN/%E8%B4%A1%E7%8C%AE/Editor_guide/Basics`,
    [`/${locale}/Apps/Packaged_apps`]:
      `/${locale}/docs/Archive/Mozilla/Marketplace/Options/%E6%89%93%E5%8C%85_%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F`,

    [`/${locale}/docs/Web/API/SpeechRecognition`]:
      `/${locale}/docs/Web/API/%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB`,
    // readystatechange event
    ['/en-US/docs/Web/Events/readystatechange']:
      '/zh-CN/docs/Web/Events/readystatechange%E4%BA%8B%E4%BB%B6',
    ['/zh-CN/docs/Web/Events/readystatechange']:
      '/zh-CN/docs/Web/Events/readystatechange%E4%BA%8B%E4%BB%B6',
    ['/en-US/docs/Web/Reference/Events/readystatechange']:
      '/zh-CN/docs/Web/Events/readystatechange%E4%BA%8B%E4%BB%B6',
    ['/zh-CN/docs/Web/Reference/Events/readystatechange']:
      '/zh-CN/docs/Web/Events/readystatechange%E4%BA%8B%E4%BB%B6',
    ['/zh-CN/docs/Web/Events/readystatechange_event']:
      '/zh-CN/docs/Web/Events/readystatechange%E4%BA%8B%E4%BB%B6'
  };
};

export const hardCodedRedirectUrl: Record<string, string> = {
  'http://w3c.org/2008/site/images/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'https://w3c.org/2008/site/images/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'https://mozorg.cdn.mozilla.net/media/img/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'http://mozorg.cdn.mozilla.net/media/img/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'http://www.mozilla.org/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'https://www.mozilla.org/favicon.ico':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'https://developer.cdn.mozilla.net/media/redesign/img/favicon32.png':
    'https://developer.mozilla.org/static/img/favicon32.png',
  'http://developer.cdn.mozilla.net/media/redesign/img/favicon32.png':
    'https://developer.mozilla.org/static/img/favicon32.png',
  // just an alternative, not original pic
  'https://i.picsum.photos/id/1080/6858/4574.jpg':
    'https://developer.mozilla.org/files/16869/new-york-skyline-4by3.jpg',
  // just an alternative, not original pic
  'http://www.mozilla.org/images/mozilla-banner.gif':
    'https://developer.mozilla.org/files/3811/linear_red_angles.png',
  // just an alternative, not original pic
  'https://www.mozilla.org/images/mozilla-banner.gif':
    'https://developer.mozilla.org/files/3811/linear_red_angles.png',
  // just an alternative, not original pic
  'https://www.mozilla.org/media/img/logos/firefox/logo-quantum.9c5e96634f92.png':
    'https://developer.mozilla.org/files/2917/fxlogo.png',
  // fake url, prevent external downloads
  'http://weloveiconfonts.com/api/?family=entypo':
    'https://developer.mozilla.org/static/build/styles/inject.css',
  // fake url, prevent external downloads
  'https://weloveiconfonts.com/api/?family=entypo':
    'https://developer.mozilla.org/static/build/styles/inject.css'
};
